/**
 * generate_mock_data.js
 * ─────────────────────
 * Node.js helper script to regenerate / inspect the mock data arrays.
 *
 * Run:  node mock-data/generate_mock_data.js
 *
 * The script prints statistics and optionally writes new steps_mock.js and
 * planned_days_mock.js files with values anchored to the CURRENT date, so
 * charts always appear "fresh" when demoing.
 *
 * NOTE: The committed static files already contain good data.
 *       Only run this if you want to update them to a new reference date.
 */

const fs = require("fs");
const path = require("path");

// ─── Configuration ──────────────────────────────────────────────────────────

const DAYS_BACK = 89; // how many days of history to generate
const DAYS_AHEAD = 90; // how many future days to plan

/** Step count by day-of-week [0=Sun … 6=Sat] – median values */
const BASE_STEPS = {
  0: 5800, // Sunday
  1: 9800, // Monday
  2: 9400, // Tuesday
  3: 9600, // Wednesday
  4: 9200, // Thursday
  5: 10200, // Friday
  6: 13000, // Saturday (hikes, outdoor activities)
};

/** Variance applied per day-of-week (±) */
const VARIANCE = {
  0: 1200,
  1: 1500,
  2: 1300,
  3: 1400,
  4: 1300,
  5: 1600,
  6: 2500,
};

/** Template assigned per day-of-week for planned days */
const PLANNED_TEMPLATE = {
  0: "tmpl_leicht", // Sunday
  1: "tmpl_aktiv", // Monday
  2: "tmpl_normal", // Tuesday
  3: "tmpl_aktiv", // Wednesday
  4: "tmpl_normal", // Thursday
  5: "tmpl_aktiv", // Friday
  6: "tmpl_intensiv", // Saturday
};

/** Probability (0–1) that a day has NO recorded steps (simulates missed days) */
const MISS_PROBABILITY = 0.04;

/** Date offsets (days from today) for planned "rest" day overrides */
const REST_DAY_OFFSETS = [19, 26, 54, 59];

// ─── Helpers ────────────────────────────────────────────────────────────────

function seededRand(seed) {
  const x = Math.sin(seed + 1) * 10000;
  return x - Math.floor(x);
}

function generateSteps(dayOfWeek, seed) {
  const base = BASE_STEPS[dayOfWeek];
  const v = VARIANCE[dayOfWeek];
  const r = seededRand(seed) * 2 - 1; // -1 … +1
  return Math.round(base + r * v);
}

function dayOffset(base, delta) {
  const d = new Date(base);
  d.setDate(d.getDate() + delta);
  return d;
}

// ─── Generate steps ─────────────────────────────────────────────────────────

function generateStepsArray(today) {
  const values = [];
  for (let i = 0; i <= DAYS_BACK; i++) {
    const d = dayOffset(today, i - DAYS_BACK);
    const dow = d.getDay();
    const missed = seededRand(i * 7) < MISS_PROBABILITY;
    if (missed) {
      values.push(null);
    } else {
      values.push(generateSteps(dow, i));
    }
  }
  return values;
}

// ─── Generate planned days ───────────────────────────────────────────────────

function generatePlannedArray(today) {
  const values = [];
  for (let i = 0; i < DAYS_AHEAD; i++) {
    const d = dayOffset(today, i);
    const dow = d.getDay();
    if (REST_DAY_OFFSETS.includes(i)) {
      values.push("tmpl_ruhe");
    } else {
      values.push(PLANNED_TEMPLATE[dow]);
    }
  }
  return values;
}

// ─── Stats ──────────────────────────────────────────────────────────────────

function printStats(steps) {
  const valid = steps.filter((s) => s !== null);
  const avg = Math.round(valid.reduce((a, b) => a + b, 0) / valid.length);
  const max = Math.max(...valid);
  const min = Math.min(...valid);
  const days = steps.length;
  const recorded = valid.length;
  console.log(`\nStep statistics (${days} days, ${recorded} recorded):`);
  console.log(`  Average : ${avg.toLocaleString()} steps`);
  console.log(`  Max     : ${max.toLocaleString()} steps`);
  console.log(`  Min     : ${min.toLocaleString()} steps`);
  console.log(`  Missed  : ${days - recorded} days`);
}

// ─── File writers ────────────────────────────────────────────────────────────

function writeStepsMock(steps, today) {
  const formatted = steps
    .map((v, i) => {
      const d = dayOffset(today, i - DAYS_BACK);
      const label = d.toLocaleDateString("de-DE", {
        weekday: "short",
        day: "numeric",
        month: "short",
      });
      return `  ${v === null ? "null" : String(v).padStart(5)}, // ${label}`;
    })
    .join("\n");

  const content = `/**
 * Mock step data for demo mode – auto-generated by generate_mock_data.js.
 * Reference date: ${today.toISOString().slice(0, 10)}
 *
 * stepsPerDay[0] = ${DAYS_BACK} days ago, stepsPerDay[${DAYS_BACK}] = today.
 * null = no entry recorded.
 */
export const stepsPerDay = [
${formatted}
];
`;
  const outPath = path.join(__dirname, "steps_mock.js");
  fs.writeFileSync(outPath, content, "utf8");
  console.log(`\nWrote: ${outPath}`);
}

function writePlannedMock(planned, today) {
  const formatted = planned
    .map((v, i) => {
      const d = dayOffset(today, i);
      const label = d.toLocaleDateString("de-DE", {
        weekday: "short",
        day: "numeric",
        month: "short",
      });
      return `  ${v === null ? "null" : `"${v}"`}, // ${label}`;
    })
    .join("\n");

  const content = `/**
 * Mock planned days for demo mode – auto-generated by generate_mock_data.js.
 * Reference date: ${today.toISOString().slice(0, 10)}
 *
 * templateIdPerDay[0] = today, [N] = today + N days.
 * null = unplanned day.
 */
export const templateIdPerDay = [
${formatted}
];
`;
  const outPath = path.join(__dirname, "planned_days_mock.js");
  fs.writeFileSync(outPath, content, "utf8");
  console.log(`Wrote: ${outPath}`);
}

// ─── Main ────────────────────────────────────────────────────────────────────

const today = new Date();
today.setHours(0, 0, 0, 0);

const steps = generateStepsArray(today);
const planned = generatePlannedArray(today);

printStats(steps);

const args = process.argv.slice(2);
if (args.includes("--write")) {
  writeStepsMock(steps, today);
  writePlannedMock(planned, today);
  console.log("\nDone. Commit the updated mock files.");
} else {
  console.log(
    "\nDry run – pass --write to overwrite mock files:\n" +
      "  node mock-data/generate_mock_data.js --write\n",
  );
}
